### ISSUE TITLE
Dependency issue while deploying apk .

### ISSUE THREAD

**Issue by nikhil-pagalguy** [KingsMentor/MobileVisionBarcodeScanner#12]
After adding the dependency, build gets generated. But when its deployed to device. Following error occurs. Is it due to some cyclic dependency available in multiple libs? Help needed slightly urgent....

02-20 04:54:26.502 6422-6422/com.softcell.gonogo.gonogohdbfs E/AndroidRuntime: FATAL EXCEPTION: main
                                                                               Process: com.softcell.gonogo.gonogohdbfs, PID: 6422
                                                                               java.lang.NoSuchMethodError: No static method zzb(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object; in class Lcom/google/android/gms/common/internal/zzaa; or its super classes (declaration of 'com.google.android.gms.common.internal.zzaa' appears in /data/app/com.softcell.gonogo.gonogohdbfs-1/split_lib_dependencies_apk.apk:classes11.dex)
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.zza(Unknown Source)
                                                                                   at com.google.firebase.provider.FirebaseInitProvider.attachInfo(Unknown Source)
                                                                                   at android.app.ActivityThread.installProvider(ActivityThread.java:4999)
                                                                                   at android.app.ActivityThread.installContentProviders(ActivityThread.java:4594)
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4534)
                                                                                   at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                                   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
                                                                                   at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                   at android.os.Looper.loop(Looper.java:135)
                                                                                   at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                   at java.lang.reflect.Method.invoke(Native Method)
                                                                                   at java.lang.reflect.Method.invoke(Method.java:372)
                                                                                   at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                                   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

These are my dependencies:

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile files('src/main/libs/android-async-http-1.4.4.jar')
    compile('com.github.afollestad.material-dialogs:core:0.8.5.7@aar') {
        transitive = true
    }
    // for joda

    // For realm with observable in jackson

    //PDF library

    //    compile 'com.joanzapata.pdfview:android-pdfview:1.0.4@aar'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    // Toast on network library error

    //disk lru cache

    // PDF library for Lollipop
    compile files('libs/protobuf_2_4_1.jar')
    compile files('libs/SamsungIndiaIdentity.jar')
    compile files('libs/xom-1.2.10.jar')
    // Testing dependency
    androidTestCompile('com.android.support.test.espresso:espresso-contrib:2.0') {
        exclude group: 'com.android.support', module: 'appcompat'
        exclude group: 'com.android.support', module: 'support-v4'
        exclude module: 'recyclerview-v7'
    }
    compile project(':gradle-git-version-master')
    configurations.all {
        resolutionStrategy.force 'com.android.support:support-annotations:23.1.0'
    }
    compile 'com.android.support:recyclerview-v7:23.4.0'
    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.android.support:design:23.4.0'
    compile 'uk.co.chrisjenx:calligraphy:2.1.0'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'com.mobsandgeeks:android-saripaar:2.0.3'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'com.fasterxml.jackson.core:jackson-core:2.7.3'
    compile 'com.fasterxml.jackson.core:jackson-annotations:2.7.3'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.7.3'
    compile 'joda-time:joda-time:2.9.2'
    compile 'io.reactivex:rxjava:1.1.0'
    compile 'com.android.support:multidex:1.0.1'
    compile 'com.github.PhilJay:MPAndroidChart:v2.2.4'
    compile 'com.github.nisrulz:easydeviceinfo:2.0.1'
    compile 'com.github.johnkil.android-appmsg:appmsg:1.2.0'
    compile 'cat.ereza:customactivityoncrash:1.5.0'
    compile 'com.google.android.gms:play-services-analytics:9.0.0'
    compile 'com.jakewharton:disklrucache:2.0.2'
    compile 'es.voghdev.pdfviewpager:library:1.0.1'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.github.bumptech.glide:glide:3.7.0'
    compile 'com.android.support.constraint:constraint-layout:1.0.0-alpha4'

    compile('com.github.KingsMentor:MobileVisionBarcodeScanner:v1.2') { transitive = true; } // This is for barcode and QR code reader

    testCompile 'junit:junit:4.12'
    testCompile 'org.mockito:mockito-core:1.10.19'
    androidTestCompile 'com.android.support.test:runner:0.5'
    androidTestCompile 'com.android.support.test.espresso:espresso-core:2.2.2'
    androidTestCompile 'com.android.support:support-annotations:23.3.0'

}

**Comment by KingsMentor** [comment]
@nikhil-pagalguy , I don't think this is due to any cyclic dependency. Gradle would flag a similar message in such scenerio. Are you certain this error shows up only when the library is included ?
